apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foloup-ingress
  namespace: foloup
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - foloup.myella.app
      secretName: foloup-tls
  rules:
    - host: foloup.myella.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: foloup-service
                port:
                  number: 9021
