apiVersion: v1
kind: Service
metadata:
  name: foloup-service
  namespace: foloup
spec:
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      port: 9021
      targetPort: 3000
  type: ClusterIP
